"""initial

Revision ID: 547cdc1ff6e3
Revises: 5c89a726934c
Create Date: 2023-10-19 07:30:08.856592

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '547cdc1ff6e3'
down_revision = '5c89a726934c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_specs_id', sa.Integer(), nullable=False),
    sa.Column('length', sa.String(length=255), nullable=False),
    sa.Column('width', sa.String(length=255), nullable=False),
    sa.Column('height', sa.String(length=255), nullable=False),
    sa.Column('wheelbase', sa.String(length=255), nullable=False),
    sa.Column('turning_circle', sa.String(length=255), nullable=False),
    sa.Column('permissible_gross_weight', sa.String(length=255), nullable=False),
    sa.Column('max_load', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_specs_id', sa.Integer(), nullable=False),
    sa.Column('top_track_speed', sa.String(length=255), nullable=False),
    sa.Column('zero_to_100_kmh', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motor_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_specs_id', sa.Integer(), nullable=False),
    sa.Column('bore', sa.String(length=255), nullable=False),
    sa.Column('stroke', sa.String(length=255), nullable=False),
    sa.Column('displacement', sa.String(length=255), nullable=False),
    sa.Column('max_power', sa.String(length=255), nullable=False),
    sa.Column('max_power_rpm', sa.String(length=255), nullable=False),
    sa.Column('max_engine_speed', sa.String(length=255), nullable=False),
    sa.Column('max_torque', sa.String(length=255), nullable=False),
    sa.Column('max_torque_rpm', sa.String(length=255), nullable=False),
    sa.Column('max_power_per_liter', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['car_specs_id'], ['car_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=72),
               existing_nullable=False)
    op.drop_table('motor_specs')
    op.drop_table('car_specs')
    op.drop_table('performance_specs')
    op.drop_table('car_model')
    op.drop_table('car_category')
    op.drop_table('car')
    op.drop_table('body_specs')
    # ### end Alembic commands ###
