"""Add car specs

Revision ID: 59a979081b51
Revises: b6f2062c6029
Create Date: 2023-10-28 10:35:37.159051

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '59a979081b51'
down_revision = 'b6f2062c6029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'body_specs', 'car_specs', ['car_specs_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('motor_specs_car_specs_id_fkey', 'motor_specs', type_='foreignkey')
    op.create_foreign_key(None, 'motor_specs', 'car_specs', ['car_specs_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'performance_specs', 'car_specs', ['car_specs_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performance_specs', type_='foreignkey')
    op.drop_constraint(None, 'motor_specs', type_='foreignkey')
    op.create_foreign_key('motor_specs_car_specs_id_fkey', 'motor_specs', 'car_specs', ['car_specs_id'], ['id'])
    op.drop_constraint(None, 'body_specs', type_='foreignkey')
    # ### end Alembic commands ###
