"""Add category id to car

Revision ID: b6f2062c6029
Revises: 547cdc1ff6e3
Create Date: 2023-10-21 19:23:28.605461

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b6f2062c6029'
down_revision = '547cdc1ff6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('car_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'car', 'car_category', ['car_category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='foreignkey')
    op.drop_column('car', 'car_category_id')
    # ### end Alembic commands ###
