"""Add highlights

Revision ID: c947c219ce44
Revises: 59a979081b51
Create Date: 2023-11-14 06:26:56.273639

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'c947c219ce44'
down_revision = '59a979081b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('paragraph', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('car_specs_car_id_fkey', 'car_specs', type_='foreignkey')
    op.create_foreign_key(None, 'car_specs', 'car', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_specs', type_='foreignkey')
    op.create_foreign_key('car_specs_car_id_fkey', 'car_specs', 'car', ['car_id'], ['id'])
    op.drop_table('highlight')
    # ### end Alembic commands ###
