"""Add highlights foreignkey

Revision ID: fde063d63fb0
Revises: c947c219ce44
Create Date: 2023-11-14 06:27:59.641839

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'fde063d63fb0'
down_revision = 'c947c219ce44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highlight', sa.Column('car_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'highlight', 'car', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highlight', type_='foreignkey')
    op.drop_column('highlight', 'car_id')
    # ### end Alembic commands ###
